language: go
arch:
  - amd64
  - ppc64le
sudo: false
go:
  - 1.x
  - tip
install:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
  - go build ./{cmd,pkg}/...
script:
  - go vet ./{cmd,pkg}/...
  - go test -v -race ./{cmd,pkg}/...
